variable "role_name" {}
variable "role_env" {}
variable "role_build_by" {}
variable "policy_name" {}
variable "policy_attachment_name" {}
variable "user_iam_name" {}
variable "minimum_password_length" {}
variable "require_lowercase_characters" {}
variable "password_reset_required" {}
variable "require_numbers" {}
variable "require_uppercase_characters" {}
variable "require_symbols" {}
variable "allow_users_to_change_password" {}
variable "cognito_policy" {}
variable "user_on_project" {}
variable "user_env" {}
variable "tags_for_user" {}
variable "region" {}

variable "ec2_ami" {}
variable "instance_type" {}
variable "pem_file_key_name" {}
variable "instance_role_profile_name" {}
variable "subnet_name" {}
variable "pgp_key" {}
