variable "domain_name" {}
variable "pool_user_name" {}
variable "password_lentgth" {}
variable "require_lowercase" {}
variable "require_uppercase" {}
variable "password_require_numbers" {}
variable "password_require_symbols" {}
variable "cognito_tag_name" {}
variable "infra_managed_by" {}
variable "environment_types" {}
variable "project_name" {}
variable "clinet_name" {}
variable "callback_urls" {}
variable "logout_urls" {}
variable "allowed_oauth_flows_user_pool_client" {}
variable "schema_attribute_emial_required" {}
variable "region" {}
