variable "subnet_name" {}
variable "ec2_ami_id" {}
variable "instance_type" {}
variable "ec2-server-name" {}
variable "ec2-server-environment" {}
variable "ec2-service-owner" {}
variable "key_pair_name" {}
variable "region" {}
variable "vpc" {}
variable "public_subnet" {}
variable "security_group" {}
variable "vpc_name" {}
#variable "iam_instance_profile" {}
