variable "region" {}
variable "main_vpc_cidr" {}
variable "public_subnets_01" {}
variable "private_subnets_01" {}
variable "public_subnets_02" {}
variable "private_subnets_02" {}
variable "zone2b" {}
variable "zone2c" {}
variable "vpc_name" {}
variable "creator_name" {}
variable "environment_name" {}
variable "managedby" {}
variable "igw_name" {}
variable "pub_subnet_01_name" {}
variable "pub_subnet_02_name" {}
variable "private_subnet_01_name" {}
variable "private_subnet_02_name" {}
variable "nat_gateway" {}
variable "pub_rt" {}
variable "private_rt" {}
